---
- name: Updating apt cache
  apt:
    update_cache: yes

- name: Installing Aptitude for Ansible to use
  apt:
    name: aptitude
    state: present

- name: Safely upgrading installed packages
  apt:
    upgrade: "safe"

- name: Installing packages
  apt:
    name: "{{ packages }}"
    state: present
