---
- name: Adding dropbox repository key
  apt_key:
    keyserver: pgp.mit.edu
    id: 1C61A2656FB57B7E4DE0F4C1FC918B335044912E

- name: Adding dropbox repository
  apt_repository:
    repo: deb http://linux.dropbox.com/ubuntu {{ ansible_lsb.codename }} main

- name: Adding dropbox
  apt:
    name: dropbox
    update_cache: yes
    state: present
