---
- name: Installing spotify repository key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90

- name: Adding spotify repository
  apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    state: present

- name: Installing spotify client
  apt:
    name: spotify-client
    update_cache: yes
    state: present
