---
- name: Adding vscode repository key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Adding vscode repository
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    filename: vscode
    state: present

- name: Installing vscode
  apt:
    name: code
    state: present
    update_cache: yes

- name: Increasing fs.inotify.max_user_watches
  sysctl:
    name: fs.inotify.max_user_watches
    value: 524288
    state: present
    reload: yes
