---
- name: Adding vscode repository key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Adding vscode repository
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present

- name: Installing vscode
  apt:
    name: code
    state: present
    update_cache: yes
